apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app
build:
  artifacts:
  - context: app
    image: istio-503-uc
    docker:
      dockerfile: app/Dockerfile
deploy:
  kubectl:
    manifests:
    - app/k8s-deployment.yaml
