apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app
build:
  artifacts:
  - context: app
    image: ghcr.io/mjasion/istio-upstream-reset
    docker:
      dockerfile: app/Dockerfile
deploy:
  kubectl:
    manifests:
    - app/k8s-*.yaml
