apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapps
  namespace: argocd
spec:
  project: default
  source:
    path: 'k8s/'
    repoURL: 'https://github.com/mjasion/istio-503-uc.git'
    targetRevision: main
    directory:
      recurse: true
  destination:
    name: ''
    namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=orphan
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.failurePolicy'
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
