apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-crd
  namespace: argocd
spec:
  project: default
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.13.2
    helm:
      releaseName: istio-base
  destination:
    namespace: 'istio-system'
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=orphan
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.13.2
    helm:
      releaseName: istiod
  destination:
    namespace: 'istio-system'
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=orphan
