apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-chunked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-chunked
  template:
    metadata:
      labels:
        app: http-chunked
    spec:
      containers:
      - name: http-chunked
        image: ghcr.io/mjasion/istio-503-uc:main
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            port: 8080
            path: /health
---
apiVersion: v1
kind: Service
metadata:
  name: http-chunked
spec:
  type: ClusterIP
  selector:
    app: http-chunked
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: http-chunked
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: http-chunked
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - http-chunked.istio-system
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: http-chunked.default.svc.cluster.local