apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: app
build:
  artifacts:
  - image: ghcr.io/mjasion/istio-503-uc
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
